parameters:
    db_common_name: '%env(DATABASE_COMMON_NAME)%'
    db_common_user: '%env(DATABASE_COMMON_USER)%'
    db_common_host: '%env(DATABASE_COMMON_HOST)%'
    db_common_password: '%env(DATABASE_COMMON_PASSWORD)%'

doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                dbname: '%db_common_name%'
                host: '%db_common_host%'
                user: '%db_common_user%'
                password: '%db_common_password%'

            tenant:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                wrapper_class: 'App\Service\TenantConnectionWrapper'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Common:
                        is_bundle: false
                        mapping: true
                        type: xml
                        dir: "%kernel.root_dir%/../config/doctrine/orm/default"
                        prefix: App\Entity\Common
                        alias: Common

            tenant:
                connection: tenant
                mappings:
                    Shop:
                        is_bundle: false
                        mapping: true
                        type: xml
                        dir: "%kernel.root_dir%/../config/doctrine/orm/shop"
                        prefix: App\Entity\Shop
                        alias: Shop