version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/var/lib/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            network_bridge:
                ipv4_address: 172.18.0.4
    php:
        build:
            context: build/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - "9000:9000"
        volumes:
            - ./build/php7-fpm/cfg/custom.ini:/usr/local/etc/php/conf.d/custom.ini:cached
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
            - ./.data/var/log/symfony:/var/www/symfony/var/log:cached
        networks:
            network_bridge:
                ipv4_address: 172.18.0.3
    nginx:
        build: build/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./.data/var/log/nginx/:/var/log/nginx:cached
        networks:
            network_bridge:
                ipv4_address: 172.18.0.2
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./build/elk/logstash:/etc/logstash:cached
            - ./build/elk/logstash/patterns:/opt/logstash/patterns:cached
        volumes_from:
            - php
            - nginx
        networks:
            network_bridge:
                ipv4_address: 172.18.0.5
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        networks:
            network_bridge:
                ipv4_address: 172.18.0.6

networks:
    network_bridge:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: shop
            config:
                - subnet: 172.18.0.0/24
                  gateway: 172.18.0.1
